### PR TITLE
create new case for feereceiver burn method.

### PR DESCRIPTION
**Pull request by EricBlack**

### CODE REVIEW

**Comment by loning** [comment]
if you faces some test can not pass, make it skip and add a todo comment.

**Comment by loning** [comment]
@EricBlack

**Comment by EricBlack** [comment]
@loning, I have add a new issue #1227 to follow this, and also copied ignored test case in issue description. When the issue fixed I will remove ignore test flag.

**Comment by loning** [comment]
todo can save your time

发自我的 iPhone

**Pull request merged**
