### PR TITLE
Unified the readme

### PR DESCRIPTION
**Pull request by Nikolaj-K**
license?

### CODE REVIEW

**Comment by xtaci** [comment]
thanks bro.

**Comment by xtaci** [comment]
@Nikolaj-K thanks, we've logged your contribution, and we will send you some ELF token later.

**Comment by Nikolaj-K** [comment]
Thank you, @xtaci. 
Given the two messages, it appears you have two different people pushing from one account. If that's the case, I'd suggest you refrain from that, for various reasons. Not the least of which is that it makes the repo appear like only few people are working on it.
On the Telegram group, I was forwarded to talk with the actual devs on the project. As I'm interested in smart contract platforms, could you shine a light on how the development effort is structured for Grid/Aelf?
I did some smart contract programming on NEO and/but am mostly interested in functional approaches. Although I suppose a Chinese project will be very much .NET oriented. Can you say something about the smart contract language you plan on implementing and what your outlook is for the VM and what you want to improve over existing approaches (more technical than that Whitepaper).
In any case, I've been interviewing developers before and if they are interested, I'd like to talk and maybe interview the main devs for the project. I'll give such types of content exposition on my youtube channel
https://www.youtube.com/channel/UCcrSMnEYhIPX_p127jI23qw/videos

If you want to reward contribution, can you clarify the scope or where you think you're lacking so - if I decide to look into it - can contribute in a meaningful and helpful way?

Take care,
Nikolaj

**Comment by xtaci** [comment]
@Nikolaj-K 

As a matter of fact, **you don’t need the concept of VM**.

A smart contract is a piece of code for making changes to the current world state, which can be formalized as:

**worldstate = apply(tx, partial(world state)) + worldstate**

note that the **apply** procedure is not bounded to anything about VM,  it just make changes. like bitcoin and ethereum are making use of the different languages to apply transaction to the current world state.

strictly speaking, you can write in any language you like, and let the **apply procedure** to be a service.

**Notes on other smart contract languages**:

**Functional approach**, personally I love functional approach for critical environment like composing smart contract for token issue, especially for it’s immutable behavior, and some FP provides program verification(eg F*).

**Dataflow approach**, like MapReduce/ReactiveX streaming processing, which is non-turing complete, but provides a powerful way for handling large sets for data computing.

**Imperative approach**, yes, solidity, it’s turing complete, but it’s error-prone.

so, I think it’s better to leave the choices to the side chain for their scenario, we provide the infrastructure for applying different contracts.

**Comment by Nikolaj-K** [comment]
Thanks for the reply. I'll look into how you then manage consensus over outcome/new state.

**Comment by Nikolaj-K** [comment]
Could you maybe outline where, if you build a community, you'd need the most help with. I'd actually put that one the progress reports to encourage people to get involved technically. And build instructions. 
You also spoke about rewards, but you never asked for an address. To the extent that I understood the project, I'm interested in how I can get involved more intricately and hook to the net.

**Pull request merged**
